apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cell-apps
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
      generators:
        - git:
            repoURL: &repo https://github.com/argoproj/argo-cd.git
            revision: HEAD
            files:
              - path: cells/cells.yaml
        - list:
            elementsYaml: "{{ .cells | toJson }}"

  template:
    metadata:
      name: "{{.name}}"
    spec:
      project: default
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      sources:
        - repoURL: *repo
          targetRevision: HEAD
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{.platform}}-{{.environment}}-{{.name}}"
