apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hyperlocal-cells
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
          - matrix:
              generators:
                - git:
                    repoURL: &repo https://github.com/ronban/argo-appset.git
                    revision: HEAD
                    directories:
                      - path: "cells/*/*/*"
                    values:
                      cell: "{{ index .path.segments 1 }}"
                      tenant: "{{ index .path.segments 2 }}"
                      module: "{{ index .path.segments 3 }}"

                - git:
                    repoURL: *repo
                    revision: HEAD
                    files:
                      - path: "cells/{{ .values.cell }}/cell.json"
                    values:

          - clusters:
              selector:
                matchExpressions:
                  - key: region
                    operator: In
                    values:
                      - "{{ .cellSpec.region }}"
                  - key: platform
                    operator: In
                    values:
                      - "{{ .cellSpec.platform }}"
                  - key: environment
                    operator: In
                    values:
                      - "{{ .cellSpec.environment }}"
                  - key: tier
                    operator: In
                    values:
                      - "{{ .cellSpec.tier }}"
  template:
    metadata:
      name: "{{ .values.cell }}-{{ .values.tenant }}-{{ .values.module }}"
    spec:
      project: default
      source:
        chart: "hyperlocal-{{ .values.module }}-helm"
        repoURL: "c.wlabs.cloud/hyperlocal-helms"
        targetRevision: '{{ index .cellPackVersions .values.module | default "latest" }}'
        helm:
          valueFiles:
            - cells/{{ .values.cell }}/{{ .values.tenant }}/{{ .values.module }}/values.yaml
          valuesObject:
            region: "{{ .cellSpec.region }}"
            tier: "{{ .cellSpec.tier }}"
            environment: "{{ .cellSpec.environment }}"
            platform: "{{ .cellSpec.platform }}"
            slug: "{{ .cellSpec.slug }}"
            cell: "{{ .values.cell }}"
            tenant: "{{ .values.tenant }}"
      destination:
        name: "{{ .name }}"
        server: "{{ .server }}"
        namespace: "{{ .values.cell }}-{{ .values.tenant }}-{{ .values.module }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
