apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hyperlocal-cells
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
          - git:
              repoURL: &repo https://github.com/ronban/argo-appset.git
              revision: HEAD
              files:
                - path: cells/*/*/*/kustomization.yaml
              values:
                cellName: "{{ index .path.segments 1 }}"
          - matrix:
              generators:
                - git:
                    repoURL: *repo
                    revision: HEAD
                    files:
                      - path: cells/{{ .values.cellName }}/cell.json
                - clusters: {}

  template:
    metadata:
      name: "{{ .values.cellName }}-{{ .path.basename }}"
    spec:
      project: default
      source:
        repoURL: *repo
        targetRevision: HEAD
        path: "{{ .path.path }}/kustomization.yaml"
      destination:
        name: "{{ .path.basename }}" # will be overridden by matched cluster

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
