apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hyperlocal-cells
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
          - git:
              repoURL: &repo https://github.com/ronban/argo-appset.git
              revision: HEAD
              files:
                - path: cells/*/*/*/kustomization.yaml
          - git:
              repoURL: &repo https://github.com/ronban/argo-appset.git
              revision: HEAD
              files:
                - path: cells/cells.yaml

  template:
    metadata:
      name: "{{ index .path.segments 1 }}-{{ index .path.segments 2 }}-{{ index .path.segments 3 }}"
    spec:
      project: default
      source:
        repoURL: *repo
        targetRevision: HEAD
        path: "cells/{{ .name }}/overlay/{{ .name }}"
      destination:
        name: "{{ .name }}" # will be overridden by matched cluster
        namespace: "{{ .name }}-{{ .name }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
