apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hyperlocal-cells
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
          - matrix:
              generators:
                - git:
                    repoURL: &repo https://github.com/ronban/argo-appset.git
                    revision: HEAD
                    directories:
                      - path: "cells/*/*/*"
                    files:
                      - path: "cells/{{ .values.cell }}/{{ .values.tenant }}/{{ .values.module }}/version.txt"
                    values:
                      cell: "{{ index .path.segments 1 }}"
                      tenant: "{{ index .path.segments 2 }}"
                      module: "{{ index .path.segments 3 }}"

                - git:
                    repoURL: *repo
                    revision: HEAD
                    files:
                      - path: "cells/{{ .values.cell }}/cell.json"
                    values:
                      region: "{{ .region }}"
                      platform: "{{ .platform }}"
                      environment: "{{ .environment }}"
                      tier: "{{ .tier }}"
                      slug: "{{ .slug }}"
                      versions: "{{ .versions }}"
          - clusters:
              selector:
                matchExpressions:
                  - key: region
                    operator: In
                    values:
                      - "{{ .region }}"
                  - key: platform
                    operator: In
                    values:
                      - "{{ .platform }}"
                  - key: environment
                    operator: In
                    values:
                      - "{{ .environment }}"
                  - key: tier
                    operator: In
                    values:
                      - "{{ .tier }}"
  template:
    metadata:
      name: "{{ .values.cell }}-{{ .values.tenant }}-{{ .values.module }}"
    spec:
      project: default
      source:
        chart: "{{ .values.module }}"
        repoURL: "oci://c.wlabs.cloud/hyperlocal-helms"
        targetRevision: '{{ index .values.versions .values.module | default "latest" }}'
        helm:
          valueFiles:
            - cells/{{ .values.cell }}/{{ .values.tenant }}/{{ .values.module }}/values.yaml
          values: |
            region: {{ .values.region }}
            tier: {{ .values.tier }}
            environment: {{ .values.environment }}
            platform: {{ .values.platform }}
            slug: {{ .values.slug }}
            cell: {{ .values.cell }}
            tenant: {{ .values.tenant }}
      destination:
        name: "{{ .name }}"
        server: "{{ .server }}"
        namespace: "{{ .values.cell }}-{{ .values.tenant }}-{{ .values.module }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
