apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: elements-yaml
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
          - matrix:
              generators:
                - git:
                    repoURL: &repo https://github.com/ronban/argo-appset.git
                    revision: HEAD
                    files:
                      - path: cells/cells.yaml
                - list:
                    elementsYaml: "{{ .cells | toJson }}"
          - clusters:
              selector:
                matchExpressions:
                  - key: region
                    operator: In
                    values:
                      - "{{ .region }}"
                  - key: platform
                    operator: In
                    values:
                      - "{{ .platform }}"
                  - key: environment
                    operator: In
                    values:
                      - "{{ .environment }}"
                  - key: tier
                    operator: In
                    values:
                      - "{{ .tier }}"
  template:
    metadata:
      name: "{{ .name }}-{{ .path.basename }}"
    spec:
      project: default
      source:
        repoURL: *repo
        targetRevision: HEAD
        path: "{{ .path.path }}"
      destination:
        name: "{{ .name }}-matched-cluster" # will be overridden by matched cluster
        namespace: "{{ .name }}"
      syncPolicy:
        automated:
          prune: true
