apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cell-apps
spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
          - clusters: {}
          - git:
              repoURL: &repo https://github.com/ronban/argo-appset.git
              revision: HEAD
              directories:
                - path: cells/{{}}
              values:
                files:
                  - path: cells.yaml

  template:
    metadata:
      name: "{{ range .values.cells }}{{ .name }}{{ end }}"
    spec:
      project: default
      source:
        repoURL: https://github.com/your-org/your-repo.git
        targetRevision: HEAD
        path: "apps/{{ .name }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ .name }}"
      syncPolicy:
        automated:
          prune: true
