apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hyperlocal-cells
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
          - matrix:
              generators:
                - git:
                    repoURL: &repo https://github.com/ronban/argo-appset.git
                    revision: HEAD
                    files:
                      - path: "cells/*/*/*/kustomization.yaml"
                    values:
                      cell: "{{ index .path.segments 1 }}"
                      tenant: "{{ index .path.segments 2 }}"
                      module: "{{ index .path.segments 3 }}"
                - git:
                    repoURL: &repo https://github.com/ronban/argo-appset.git
                    revision: HEAD
                    files:
                      - path: "cells/{{ .values.cell }}/cell.json"
                    values:
                      region: "{{ .region }}"
                      platform: "{{ .platform }}"
                      environment: "{{ .environment }}"
                      tier: "{{ .tier }}"
          - clusters:
              selector:
                matchExpressions:
                  - key: region
                    operator: In
                    values:
                      - "{{ .region }}"
                  - key: platform
                    operator: In
                    values:
                      - "{{ .platform }}"
                  - key: environment
                    operator: In
                    values:
                      - "{{ .environment }}"
                  - key: tier
                    operator: In
                    values:
                      - "{{ .tier }}"
  template:
    metadata:
      name: "{{ .values.cell }}-{{ .values.tenant }}-{{ .values.module }}"
    spec:
      project: default
      source:
        repoURL: *repo
        targetRevision: HEAD
        path: "{{ .path.path }}/kustomization.yaml"
      destination:
        name: "{{ .server }}" # will be overridden by matched cluster

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
