apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hyperlocal-cells
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
          - git:
              repoURL: &repo https://github.com/ronban/argo-appset.git
              revision: HEAD
              files:
                - path: cells/cell-hidden-dragon/cell.json
          - clusters:
              selector:
                matchExpressions:
                  - key: region
                    operator: In
                    values:
                      - "{{ .region }}"
                  - key: platform
                    operator: In
                    values:
                      - "{{ .platform }}"
                  - key: environment
                    operator: In
                    values:
                      - "{{ .environment }}"
                  - key: tier
                    operator: In
                    values:
                      - "{{ .tier }}"

  template:
    metadata:
      name: "{{ .region }}"
    spec:
      project: default
      source:
        repoURL: *repo
        targetRevision: HEAD
        path: "{{ .path.path }}/kustomization.yaml"
      destination:
        name: "{{ .path.basename }}" # will be overridden by matched cluster

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
