apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hyperlocal-cells
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
          - matrix:
              generators:
                - matrix:
                    generators:
                      - git:
                          repoURL: &repo https://github.com/ronban/argo-appset.git
                          revision: HEAD
                          files:
                            - path: cells/cells.yaml
                      - list:
                          elementsYaml: "{{ .cells | toJson }}"
                - clusters:
                    selector:
                      matchExpressions:
                        - key: region
                          operator: In
                          values:
                            - "{{ .region }}"
                        - key: platform
                          operator: In
                          values:
                            - "{{ .platform }}"
                        - key: environment
                          operator: In
                          values:
                            - "{{ .environment }}"
                        - key: tier
                          operator: In
                          values:
                            - "{{ .tier }}"
          - matrix:
              generators:
                - git:
                    repoURL: *repo
                    revision: HEAD
                    directories:
                      - path: cells/commons/*
                      - path: cells/tenants/*/*
  template:
    metadata:
      name: "{{ .name }}-{{ .name }}"
    spec:
      project: default
      source:
        repoURL: *repo
        targetRevision: HEAD
        path: "cells/{{ .name }}/overlay/{{ .name }}"
      destination:
        name: "{{ .name }}" # will be overridden by matched cluster
        namespace: "{{ .name }}-{{ .name }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
